### ISSUE TITLE
Actors seem to be broken leaving area2b

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#131]
Something is causing actors to not load properly. Everything was fine until I wanted to leave area2b. Save Warping out causing Samus to be in limbo in Surface (my spawn is there). Exiting via the elevator works but all the enemies are invisible and stuck at their initial spawns. Teleporting into Surface has the same outcome as Warp to Start. Reloading to checkpoint after attempting to teleport to Surface causes Samus and the Baby to be invisible. 

Update: Found the culprit. Commenting out the beam doors in area2b fixes this. Yay our favorite bug!!! :)

https://github.com/randovania/open-samus-returns-rando/assets/38679103/b4c8f013-cf5b-494a-ae98-a12c0590c6d6

![image](https://github.com/randovania/open-samus-returns-rando/assets/38679103/a050c122-697a-49d1-8e7a-f5d9d54c9932)

**Comment by dyceron** [comment]
It might not be warp to start. Something else is going on because leaving the area via the elevator causes all actors to be invisible and stuck at their initial spawns.

**Comment by ThanatosGit** [comment]
You could try to add our magic number "3" to the copied doors, add them to the entity groups again and change the door lua properly.

If that doesn't work, it's definitely a huge blocker because we are not able to add any actors without destroying the game. I already compared the output with the vanilla files, checked MEDS etc.
I'm pretty clueless why this isn't working and what to do about it.

**Comment by dyceron** [comment]
Maybe we can move the shields to an unused layer? I don't know if that would help this.
