### ISSUE TITLE
Progressive Models do not animate

### ISSUE THREAD

**Issue by dyceron** [randovania/open-samus-returns-rando#75]
https://github.com/randovania/open-samus-returns-rando/assets/38679103/d873d0cb-0c72-4463-8671-88e5a361a4a1

**Comment by ThanatosGit** [comment]
Chances are pretty low that this will ever change IMO.
Dread also has no effects or animation on progressives and we are using the same component here to achieve it.

**Comment by ThanatosGit** [comment]
As this is very likely an issue / bug which will stay open forever, we may just make a list of items we want to rotate? Iirc Wave Beam is facing towards the screen but all other stages of progressive beam are fine.
Can we rotate from lua? I don't want to implement a animation on every frame because of the heavy load but it would be nice to do it when we update the progressive model.
Otherwise the solution won't work anyways b

**Comment by dyceron** [comment]
Closing due to merged pr and the very low likelihood of this ever changing.
